openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Playground
  description: For Swagger Studying
  license:
    name: bbearcookie
servers:
  - url: http://localhost:5010/
components:
  parameters:
    $ref: './components/parameters.yaml'
  responses:
    $ref: './components/responses.yaml'
paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /posts:
    $ref: './paths/post/_.yaml'
  /posts/{postId}:
    $ref: './paths/post/{postId}/_.yaml'
  /posts/{postId}/comments:
    $ref: './paths/post/{postId}/comments.yaml'
