openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Playground
  description: For Swagger Studying
  license:
    name: bbearcookie
servers:
  - url: http://localhost:5010/

components:
  parameters:
    $ref: './components/parameters.yaml'
  responses:
    $ref: './components/responses.yaml'
  schemas:
    $ref: './components/schemas.yaml'

paths:
  /posts:
    $ref: './paths/posts/_.yaml'
  /posts/{postId}:
    $ref: './paths/posts/{postId}/_.yaml'
  /posts/{postId}/comments:
    $ref: './paths/posts/{postId}/comments.yaml'
  /comments/{commentId}:
    $ref: './paths/comments/{commentId}/_.yaml'

  /auth/signup:
    $ref: './paths/auth/signup.yaml'
  /auth/signin:
    $ref: './paths/auth/signin.yaml'
  /auth/signout:
    $ref: './paths/auth/signout.yaml'
  /auth/check:
    $ref: './paths/auth/check.yaml'
  /auth/password:
    $ref: './paths/auth/password.yaml'

  /users/{userId}:
    $ref: './paths/users/{userId}/_.yaml'
  /users/{userId}/photos:
    $ref: './paths/users/{userId}/photo.yaml'
