Authorization:
  name: Authorization
  in: header
  required: true
  description: 액세스 토큰
  schema:
    type: string
    example: Bearer {accessToken}

postId:
  name: postId
  in: path
  required: true
  description: 머쓱이의 postId
  schema:
    type: integer
    format: int64

commentId:
  name: commentId
  in: path
  required: true
  description: 편지의 commentId
  schema:
    type: integer
    format: int64
