Authorization:
  name: Authorization
  in: header
  description: 액세스 토큰
  required: true
  schema:
    type: string
    example: Bearer {accessToken}

postId:
  name: postId
  in: path
  description: 조회할 머쓱이의 postId
  required: true
  schema:
    type: integer
    format: int64

commentId:
  name: commentId
  in: path
  description: 조회할 편지의 commentId
  required: true
  schema:
    type: integer
    format: int64
